openapi: 3.0.3
info:
  title: openBD API (Fake)
  version: "1.0"
servers:
  - url: http://localhost:4011
paths:
  /get:
    get:
      summary: Get book by ISBN
      parameters:
        - name: isbn
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
              examples:
                found:
                  value:
                    - summary:
                        title: "リーダブルコード"
                        author: "Dustin Boswell, Trevor Foucher"
                        publisher: "オライリージャパン"
                        pubdate: "20120623"
                        cover: "http://example.com/cover.jpg"
                notFound:
                  value:
                    - null
components:
  schemas:
    Book:
      type: object
      nullable: true
      properties:
        summary:
          type: object
          properties:
            title:
              type: string
            author:
              type: string
            publisher:
              type: string
            pubdate:
              type: string
            cover:
              type: string
